application:
  name: GoogleDriveManager

google:
  credentials_path: ${PRIVATE_KEY:/credentials.json}
  credentials: ${PRIVATE_KEY_FILE}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASS}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: bagginsdrive@gmail.com
      text: no-reply
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    enabled: true
    path: /docs

jwt:
  secret: ${JWT_SECRET:a}
  ttl: 99999999